apiVersion: skaffold/v2beta12
kind: Config

deploy:
  kubectl:
    manifests:
      - ./k8s-dev/client-deployment.yaml
      - ./k8s-dev/server-deployment.yaml
      - ./k8s-dev/worker-deployment.yaml
      - ./k8s-dev/redis-deployment.yaml
      - ./k8s-dev/postgres-deployment.yaml
      - ./k8s-dev/client-cluster-ip-service.yaml
      - ./k8s-dev/server-cluster-ip-service.yaml
      - ./k8s-dev/redis-cluster-ip-service.yaml
      - ./k8s-dev/postgres-cluster-ip-service.yaml
      - ./k8s-dev/database-persistent-volume-claim.yaml
      - ./k8s-dev/ingress-service.yaml

build:
  local:
    push: false
  artifacts:
    - image: yetiasg/multi-client
      context: client
      docker:
        dockerfile: "Dockerfile.dev"
      sync:
        manual:
          - src: '/**/*.js'
            dest: .src
          - src: '/**/*.css'
            dest: .src
          - src: '/**/*.html'
            dest: .src

    - image: yetiasg/multi-server
      context: server
      docker:
        dockerfile: "Dockerfile.dev"
      sync:
        manual:
          - src: '/*.js'
            dest: .

    - image: yetiasg/multi-worker
      context: worker
      docker:
        dockerfile: "Dockerfile.dev"
      sync:
        manual:
          - src: '/*.js'
            dest: .